#!/usr/bin/env tsx
import assert from "node:assert";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import open from "open";
import dotenv from "dotenv";
import { getAddress, JsonRpcProvider, Contract } from "ethers";
import { CHAIN_IDS, type ChainPrefix } from "@zodiaceco/sdk/allow";
import type { Members, Permissions } from "../types";

type ChainId = (typeof CHAIN_IDS)[ChainPrefix];

const ROLES_MOD_ABI = ["function owner() view returns (address)"];

function parseMod(modArg: string) {
  const components = modArg.trim().split(":");
  assert(components.length === 2, `Invalid prefixed address: ${modArg}`);
  const [chainPrefix, modAddress] = components as [string, string];

  assert(chainPrefix in CHAIN_IDS, `Chain is not supported: ${chainPrefix}`);
  const chainId = CHAIN_IDS[chainPrefix as ChainPrefix];

  const address = getAddress(modAddress) as `0x${string}`;
  return { chainId, chainPrefix, address };
}

function run(command: string, args: string[]) {
  const result = spawnSync(command, args, { stdio: "inherit", shell: true });
  assert(result.status === 0, `\`${command} ${args.join(" ")}\` failed`);
}

async function fetchModOwner(
  chainId: ChainId,
  address: `0x${string}`,
): Promise<`0x${string}` | null> {
  const provider = new JsonRpcProvider(
    `https://rpc.gnosisguild.org/${chainId}`,
  );
  const contract = new Contract(address, ROLES_MOD_ABI, provider);
  try {
    const owner: string = await contract.getFunction("owner")();
    return getAddress(owner) as `0x${string}`;
  } catch {
    return null;
  }
}

// Workspace names as typed by `.zodiac/index.d.ts` (generated by `zodiac pull`).
type Workspace = ZodiacGeneratedCodegen extends { accounts: infer A }
  ? keyof A & string
  : string;

function firstWorkspaceName(): Workspace {
  const codegen = createRequire(import.meta.url)(
    path.resolve(process.cwd(), ".zodiac"),
  ) as { accounts: Record<string, unknown> };
  const [name] = Object.keys(codegen.accounts);
  assert(
    name,
    "No workspaces found in Zodiac org. Create one at app.zodiac.eco.",
  );
  return name as Workspace;
}

async function main() {
  const [roleArg, modArg] = process.argv.slice(2);
  if (!roleArg || !modArg) {
    console.error(
      "Usage: yarn apply <role> <chain-prefix>:<mod-address>\n\n" +
        "  role  The role key, i.e., the name of the folder in roles/\n" +
        '  mod   The chain-prefixed address of the Roles modifier, e.g. "eth:0x1234...5678"',
    );
    process.exit(1);
  }
  const { chainId, address } = parseMod(modArg);

  const owner = await fetchModOwner(chainId, address);
  assert(
    owner,
    `Address ${modArg} does not look like a Roles mod (could not read owner())`,
  );

  // `zodiac pull` auto-runs `zodiac init` (browser auth) when ZODIAC_API_KEY is
  // missing, then writes the key, fresh org codegen, contract ABIs and the
  // `allow` kit typings to disk.
  run("zodiac", ["pull"]);

  // Type-check against the freshly generated codegen before pushing anything.
  run("tsc", ["--noEmit"]);

  // Load the API key that `zodiac pull` wrote to .env, so the SDK's API client
  // sees it.
  dotenv.config({ quiet: true });

  // Import late: the `allow` kit reads the ABIs `zodiac pull` just fetched.
  await import("../globals");
  const { constellation, push } = await import("@zodiaceco/sdk");

  const permissions: Permissions = (
    await import(`../../roles/${roleArg}/permissions`)
  ).default;

  const members: Members = (await import(`../../roles/${roleArg}/members`))
    .default;

  const chain = constellation({
    workspace: firstWorkspaceName(),
    label: `Update role: ${roleArg}`,
    chain: chainId,
  });

  // Bind to the existing on-chain Roles mod by address and reconfigure only
  // this role; other roles on the mod are left untouched.
  const rolesMod = chain.roles[address]!({
    address,
    roles: {
      [roleArg]: { members, permissions },
    },
  });

  const [result] = await push([rolesMod]);
  assert(result, "push() returned no result");
  console.log("Role update pushed. Open to review and confirm:");
  console.log(result.url);
  open(result.url);
}

main();
